language: ruby

rvm:
  - 2.0.0-p598

jdk:
    - oraclejdk8

env:
  - URL=https://github.com/redpen-cc/redpen/releases/download/redpen-1.6.0

install:
  - wget $URL/redpen-1.6.0.tar.gz
  - tar xvf redpen-1.6.0.tar.gz
  - export PATH=$PATH:$PWD/redpen-distribution-1.6.0/bin

script:
  - gem install asciidoctor
  - gem install coderay
  - gem install --pre asciidoctor-pdf
  - sudo apt-get update && sudo apt-get install oracle-java8-installer
  - make check     # RedPenを適用する
  - make html      # 出力ドキュメント（HTML）の生成
  - make pdf       # 出力ドキュメント（PDF）の生成
