[[suppress-section]]
== Error Suppression

RedPenから出力されるエラー（規約違反）を修正したくない場合があります。
修正したくない場合には、エラーの修正にかかるコストが大きすぎる場合や、明確な理由をもって規約に違反する場合が含まれます。
そのような場合に対応するために、RedPenはアノテーションによってエラーを抑制する機能（**エラー抑制機能**）があります。機能を使うには、特殊なアノテーション（**抑制アノテーション**）をエラーを含むセクションの直前に書きます。
現在、エラー抑制機能は4つ（AsciiDoc・Markdown・Re:VIEW・LaTeX）のフォーマットで使えます。

=== AsciiDoc

AsciiDocでエラー抑制機能を使うには、抑制アノテーションをアトリビュートブロックに書きます。抑制アノテーションは **[suppress]** です。次は、ある節について全てのエラーを抑制する例です。

```asciidoc
[suppress]
= Instances
Some software tools work in more than one machine, and such distributed (cluster)systems can handle huge data or tasks, because such software tools make use of large amount of computer resources, such as CPU, Disk, and Memory.
```

When the writers want to suppress only the specified errors, they add Validator names after **suppress**. For example, the following example suppresses only two types of errors (Contraction WeakExpression).
一部のエラーのみを抑制する場合、抑制アノテーション（**suppress**）にバリデータ名を続けて書きます。次は、ある節について2種類のエラー（Contraction・WeakExpression）のみを抑制する例です。


```asciidoc
[suppress='Contraction WeakExpression']
= Instances
Some software tools work in more than one machine, and such distributed (cluster)systems can handle huge data or tasks, because such software tools make use of large amount of computer resources, such as CPU, Disk and Memory.
```

NOTE: 複数行にわたるセクションでは、エラー抑制機能を使用できません。

=== Markdown

Markdownフォーマットの文書でエラー抑制機能を使うには、HTMLコメント内に抑制アノテーションを書きます。抑制アノテーションは **@suppress** です。
以下に示す例では、あるセクションについて全てのエラーを抑制する例です。

```markdown
<!-- @suppress -->
# Instances
Some software tools work in more than one machine, and such _distributed_ (cluster)systems can handle huge data or tasks, because such software tools make use of large amount of computer resources, such as CPU, Disk and Memory.
```

一部のエラーのみを抑制するには、バリデータ名を抑制アノテーション（**@suppress**）に続けて書きます。次の例では2種類のエラー（Contraction・WeakExpression）のみを抑制しています。

```markdown
<!-- @suppress Contraction WeakExpression -->
# Instances
Some software tools work in more than one machine, and such _distributed_ (cluster)systems can handle huge data or tasks, because such software tools make use of large amount of computer resources, such as CPU, Disk and Memory.
```

NOTE: 複数行に渡るHTMLコメント内では抑制アノテーションは機能しません。

=== Re:VIEW

Re:VIEWフォーマットの文書でエラー抑制機能を使うには、Re:VIEWコメント（"\#@#"）内に抑制アノテーションを書きます。抑制アノテーションは **@suppress** です。
以下に示す例では、あるセクションについて全てのエラーを抑制する例です。

```
#@# @suppress
= Instances
Some software tools work in more than one machine, and such distributed (cluster)systems can handle huge data or tasks, because such software tools make use of large amount of computer resources, such as CPU, Disk and Memory.
```

一部のエラーのみを抑制するには、バリデータ名を抑制アノテーション（**@suppress**）に続けて書きます。次の例では2種類のエラー（Contraction・WeakExpression）のみを抑制しています。

```
#@# @suppress Contraction WeakExpression
= Instances
Some software tools work in more than one machine, and such distributed (cluster)systems can handle huge data or tasks, because such software tools make use of large amount of computer resources, such as CPU, Disk and Memory.
```

=== LaTeX

LaTeXフォーマットの文書でエラー抑制機能を使うには、LaTeXコメント（%）内に抑制アノテーションを記述します。記述する抑制アノテーションはMarkdownフォーマットの文書の場合と同じです。
