[[suppress-section]]
== エラー抑制機能

RedPen から出力されるエラー（規約違反）を修正したくない場合があります。
修正したくない場合には、エラーの修正にかかるコストが大きすぎる場合や、明確な理由をもって規約に違反する場合が含まれます。
修正したくない場合に対応するために、RedPen はアノテーションによってエラーを抑制する機能（**エラー抑制機能**）があります。機能を使うには、特殊なアノテーション（**抑制アノテーション**）をエラーを含むセクションの直前に書きます。
現在、エラー抑制機能は四つ（AsciiDoc ・ Markdown ・ Re:VIEW ・ LaTeX）のフォーマットで使えます。

=== AsciiDoc

AsciiDoc でエラー抑制機能を使うには、抑制アノテーションをアトリビュートブロックに書きます。抑制アノテーションは **+++[suppress]+++** です。次は、ある節について全てのエラーを抑制する例です。

[source,asciidoc]
----
[suppress]
= Instances
Some software tools work in more than one machine, and such distributed (cluster)systems can handle huge data or tasks, because such software tools make use of large amount of computer resources, such as CPU, Disk, and Memory.
----

一部のエラーのみを抑制する場合、抑制アノテーション（**suppress**）にバリデータ名を続けて書きます。次は、ある節について2種類のエラー（Contraction ・ WeakExpression）のみを抑制する例です。


[source,asciidoc]
----
[suppress='Contraction WeakExpression']
= Instances
Some software tools work in more than one machine, and such distributed (cluster)systems can handle huge data or tasks, because such software tools make use of large amount of computer resources, such as CPU, Disk and Memory.
----

NOTE: 複数行にわたるセクションでは、エラー抑制機能を使用できません。

=== Markdown

Markdown フォーマットの文書でエラー抑制機能を使うには、 HTML コメント内に抑制アノテーションを書きます。抑制アノテーションは **+++@suppress+++** です。
以下に示す例では、あるセクションについて全てのエラーを抑制する例です。

[source,markdown]
----
<!-- @suppress -->
# Instances
Some software tools work in more than one machine, and such _distributed_ (cluster)systems can handle huge data or tasks, because such software tools make use of large amount of computer resources, such as CPU, Disk and Memory.
----

一部のエラーのみを抑制するには、バリデータ名を抑制アノテーション（**+++@suppress+++**）に続けて書きます。次の例では2種類のエラー（Contraction ・ WeakExpression）のみを抑制しています。

[source,markdown]
----
<!-- @suppress Contraction WeakExpression -->
# Instances
Some software tools work in more than one machine, and such _distributed_ (cluster)systems can handle huge data or tasks, because such software tools make use of large amount of computer resources, such as CPU, Disk and Memory.
----

NOTE: 複数行に渡る HTML コメント内では抑制アノテーションは機能しません。

=== Re:VIEW

Re:VIEW フォーマットの文書でエラー抑制機能を使うには、Re:VIEW コメント（ ``+++#@#+++`` ）内に抑制アノテーションを書きます。抑制アノテーションは **+++@suppress+++** です。
以下に示す例では、あるセクションについて全てのエラーを抑制する例です。

[source]
----
#@# @suppress
= Instances
Some software tools work in more than one machine, and such distributed (cluster)systems can handle huge data or tasks, because such software tools make use of large amount of computer resources, such as CPU, Disk and Memory.
----

一部のエラーのみを抑制するには、バリデータ名を抑制アノテーション（**+++@suppress+++**）に続けて書きます。次の例では2種類のエラー（Contraction ・ WeakExpression）のみを抑制しています。

[source]
----
#@# @suppress Contraction WeakExpression
= Instances
Some software tools work in more than one machine, and such distributed (cluster)systems can handle huge data or tasks, because such software tools make use of large amount of computer resources, such as CPU, Disk and Memory.
----

=== LaTeX

LaTeX フォーマットの文書でエラー抑制機能を使うには、LaTeX コメント（ `+++%+++` ）内に抑制アノテーションを記述します。記述する抑制アノテーションは Markdown フォーマットと同じです。
